<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ezyybin604.yesrandom2d</groupId>
    <artifactId>YesRandom2D</artifactId>
    <version>0.2-dev</version>

    <name>YesRandom2D</name>
    <url>https://github.com/ezyybin604/yesrandom2d</url>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>
    
    <build>
        <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <version>3.5.1</version>
            <artifactId>maven-jar-plugin</artifactId>
            <configuration>
            <archive>
                <manifest>
                <addClasspath>true</addClasspath>
                <mainClass>com.ezyybin604.yesrandom2d.Main</mainClass>
                </manifest>
            </archive>
            </configuration>
        </plugin>
    </plugins>
  </build>

</project>